//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalShop.Shared.Resources.Services.CartService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CartServiceErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CartServiceErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalShop.Shared.Resources.Services.CartService.CartServiceErrors", typeof(CartServiceErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در اضافه کردن آیتم به سبد خرید.
        /// </summary>
        public static string AddCartItemProblem {
            get {
                return ResourceManager.GetString("AddCartItemProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم موردنظر در سبد خرید یافت نشد.
        /// </summary>
        public static string CartItemNotFound {
            get {
                return ResourceManager.GetString("CartItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبد خرید یافت نشد.
        /// </summary>
        public static string CartNotFound {
            get {
                return ResourceManager.GetString("CartNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در حذف آیتم از سبد خرید.
        /// </summary>
        public static string DeleteCartItemProblem {
            get {
                return ResourceManager.GetString("DeleteCartItemProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در حذف محصول از تمام کارت ها.
        /// </summary>
        public static string DeleteProductInCartsCommandProblem {
            get {
                return ResourceManager.GetString("DeleteProductInCartsCommandProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول مورد نظر یافت نشد.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی محصول مورد نظر کافی نمی باشد.
        /// </summary>
        public static string ProductStockNotEnough {
            get {
                return ResourceManager.GetString("ProductStockNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در بروزرسانی آیتم در سبد خرید.
        /// </summary>
        public static string UpdateCartItemProblem {
            get {
                return ResourceManager.GetString("UpdateCartItemProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در بروزرسانی محصول در تمام کارت ها.
        /// </summary>
        public static string UpdateProductInCartsCommandProblem {
            get {
                return ResourceManager.GetString("UpdateProductInCartsCommandProblem", resourceCulture);
            }
        }
    }
}
