//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalShop.Resources.Services.TagService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TagServiceErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TagServiceErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalShop.Resources.Services.TagService.TagServiceErrors", typeof(TagServiceErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در ساختن تگ مورد نظر.
        /// </summary>
        public static string CreateTagProblem {
            get {
                return ResourceManager.GetString("CreateTagProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در حذف کردن تگ مورد نظر.
        /// </summary>
        public static string DeleteTagProblem {
            get {
                return ResourceManager.GetString("DeleteTagProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تگ مورد نظر یافت نشد.
        /// </summary>
        public static string TagNotFound {
            get {
                return ResourceManager.GetString("TagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط کاربر سازنده تگ می تواند عمل موردنظر را اعمال کند.
        /// </summary>
        public static string TagOwnerMatchProblem {
            get {
                return ResourceManager.GetString("TagOwnerMatchProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در بروزرسانی تگ مورد نظر.
        /// </summary>
        public static string UpdateTagProblem {
            get {
                return ResourceManager.GetString("UpdateTagProblem", resourceCulture);
            }
        }
    }
}
